### ISSUE TITLE
Reset needed for some targets

### ISSUE THREAD

**Issue by untaugh** [ataradov/edbg#17]
Writing a wrong clock config locks up my samd21g18, and makes me unable to program with edbg. 

I solved this by adding dap_reset_target() after dap_connect(), but this seems to introduce another problem with the chip not running after programming, until I press reset. I don't know enough about CMSIS-DAP for a proper solution yet, but I'm looking into it.

**Comment by ataradov** [comment]
This reset is not going to be a 100% solution. You are basically trying to catch the moment between your reset and setting the frequency and depending on your code it will be a different time. In many cases it will be short enough that this hack won't work. And it is actually possible to screw things up so that even reset won't help, only power cycle can recover the situation. Same problem happens with sleep sometimes.

In general it is easy to avoid. When debugging a new code that does something critical to system configuration, add small delay at the beginning of the program. This will give debugger enough time to intercept the MCU in a working state.

The problem with dap_reset_target() is that it is not actually implemented on many debuggers and its goal is slightly different from performing a simple reset.
